name: toolscosmo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pytest
  - pip
  - pip:
    - -r requirements.txt  # This ensures any additional pip packages are installed
